name: checksums-app
base: core24
adopt-info: version-provider
title: Checksums App
contact: support@rammini.com
license: MIT
issues: https://github.com/chamalsl/checksums_app_client/issues
source-code: https://github.com/chamalsl/checksums_app_client
website: https://checksums.app/
icon: icon.svg
summary: Application to calculate and verify SHA-256 and SHA-512 checksums.
description: |
  This application will calculate SHA-256 and SHA-512 checksums of your file.
  Then verify those checksums with checksums stored at https://checksums.app.

  Your files will not be uploaded to our server. 
  Only sha256, sha512 and file name of selected file will be sent to https://checksums.app for verification.

grade: stable #devel 
confinement: strict #devmode 

slots:
  dbus-app-checksums: 
    interface: dbus
    bus: session 
    name: app.checksums # MUST match the D-Bus name your app tries to register
    
parts: 
  version-provider:
    plugin: dump
    source: .
    override-pull: |
      craftctl default
      VERSION=$(cat VERSION)
      craftctl set version="$VERSION"   

  checksums-app:
    plugin: make
    source: .
    make-parameters:
      - BUILD=release
    override-build: |
      echo "Generate resources.cc\n"
      rm resources.cc
      glib-compile-resources --target=resources.cc --generate-source resources.xml
      craftctl default
    build-packages:
      - g++
      - make
      - libcurl4-openssl-dev 
      - libgtkmm-3.0-dev
      - libsecret-1-dev
      - libssl-dev
    stage-packages:
      - libcurl4t64
      - libgtkmm-3.0-1t64
      - libcurl3t64-gnutls
      - libsecret-1-0
      
apps:
  checksums-app:
    environment:
      #LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP_DESKTOP_RUNTIME/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:$SNAP_DESKTOP_RUNTIME/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gio/modules
    command: bin/checksums
    #desktop: snap/gui/app.checksums.desktop
    extensions: [gnome]
    slots: [dbus-app-checksums]
    plugs:
      - network
      - home
      - desktop
    

